---

- hosts: localhost
  roles:
    - role: azimuth_deploy
      when: manual_deployment == "false"

- hosts: localhost
  roles:
    - role: manual_deploy
      when: manual_deployment == "true"
  vars:
    terraform_project_path: "{{ playbook_dir }}"
    terraform_roles_path: "{{ playbook_dir }}/roles"


# Provision the infrastructure

# The CaaS puts hosts for accessing the OpenStack
# API into the 'openstack' group
- hosts: openstack
  roles:
    - cluster_infra

# If openstack_deploy is true then continue if not end the playbook.

# Import the playbook to start configuring the multi-node hosts.
- name: Configure hosts and deploy ansible
  import_playbook: ansible/configure-hosts.yml   
  when: openstack_deploy | bool


- hosts: ansible_control
  vars:
    ansible_pipelining: true
    ansible_ssh_pipelining: true
  tasks: 
    - name: Deploy OpenStack.
      ansible.builtin.command:
        cmd: "bash ~/deploy-openstack.sh"
      when: openstack_deploy | bool
  
# This is to get the ip of the ansible-controller host.
- hosts: localhost
  tasks: 
    - debug: var=outputs
      vars:
        outputs: 
          cluster_access_ip: "{{ hostvars[groups['openstack'][0]].cluster_gateway_ip }}"