---

- hosts: localhost
  tasks:    
    - name: Show Playbook Directory
      debug:
       msg: "{{ playbook_dir }}"

    - name: Generate SSH Key
      ansible.posix.ssh_keypair:
        path: "{{ playbook_dir }}/ssh_key"
        type: rsa
        size: 2048
        state: present

    - name: Template Terraform files into project directory
      template:
        src: terraform.tfvars.j2
        dest: "{{ playbook_dir }}/terraform.tfvars"

# Provision the infrastructure
# The CaaS puts hosts for accessing the OpenStack API into the 'openstack' group
- hosts: openstack
  roles:
    - cluster_infra

# Write the outputs as the final task
- hosts: localhost
  tasks:
    - debug: var=outputs
      vars:
        outputs: 
          cluster_access_ip: "{{ hostvars[groups['openstack'][0]].cluster_gateway_ip }}"
    
    - name: Show Playbook Directory
      debug:
       msg: "{{ playbook_dir }}"