---

- name: Install Terraform binary
  include_role:
    name: stackhpc.terraform.install

- name: Make Terraform project directory
  file:
    path: "{{ terraform_project_path }}"
    state: directory

- name: Write backend configuration
  copy:
    content: |
      terraform {
        backend "{{ terraform_backend_type }}" { }
      }
    dest: "{{ terraform_project_path }}/backend.tf"

- include_tasks: "{{ playbook_dir }}/roles/cluster_infra/template/appliance-patch.yml"
  when: manual_deployment == false

- name: Provision infrastructure
  include_role:
    name: stackhpc.terraform.infra