---
- name: Fix Home Directory Ownership
  hosts: all
  gather_facts: true
  vars_files:
    - files/admin-oc-networks.yml
  tasks:
    - name: Ensure homedir of all nodes is owned by cloud-user # noqa: no-changed-when
      ansible.builtin.command:
        cmd: "ssh cloud-user@{{ item.value }} sudo chown -R cloud-user: ."
      loop: "{{ admin_oc_ips | combine({'control-host': inventory_hostname}) | dict2items }}"
      delegate_to: localhost
