---
- name: Fix Home Directory Ownership
  hosts: all
  gather_facts: true
  vars:
    # At the time of running this playbook the home directory is not owned by the user.
    # Therefore, we will not be permitted to store the Ansible temporary directory in the home folder.
    # This must be relocated to some where that can be written to by the remote user.
    ansible_remote_tmp: "/tmp/ansible"
  tasks:
    - name: Ensure homedir is owned by cloud-user # noqa: no-changed-when
      ansible.builtin.file:
        dest: "{{ ansible_env.HOME }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"
      become: true
